extends Node

@export var test_data_file: String = "res://elixir_encoded_variants.bin"
@export var test_full_sync_file: String = "res://elixir_full_sync_packet.bin"
@export var test_delta_sync_file: String = "res://elixir_delta_sync_packet.bin"

func _ready():
	print("=== MultiplayerSynchronizer Compatibility Test ===")
	print("Testing actual MultiplayerSynchronizer decoding (not just spec compliance)")
	print("")
	
	# Test 1: Decode variants using MultiplayerAPI (what MultiplayerSynchronizer uses)
	test_variant_decoding()
	
	# Test 2: Decode full sync packet format
	test_full_sync_packet_decoding()
	
	# Test 3: Decode delta sync packet format
	test_delta_sync_packet_decoding()
	
	# Test 4: Verify packet can be processed by MultiplayerSynchronizer's on_sync_receive
	test_multisync_receive_handler()
	
	print("")
	print("=== All MultiplayerSynchronizer Compatibility Tests Complete ===")
	get_tree().quit(0)

func test_variant_decoding():
	print("Test 1: Variant Decoding via MultiplayerAPI (MultiplayerSynchronizer Method)")
	print("------------------------------------------------------------------------------")
	
	var file = FileAccess.open(test_data_file, FileAccess.READ)
	if file == null:
		print("⚠️  Skipping: Could not open #{test_data_file}")
		print("   Run test_elixir_to_godot.exs first to generate the file")
		return
	
	var data = file.get_buffer(file.get_length())
	file.close()
	
	print("Read ", data.size(), " bytes from Elixir-encoded file")
	print("")
	print("Testing using MultiplayerAPI::decode_and_decompress_variants() method")
	print("(This is what MultiplayerSynchronizer actually uses)")
	print("")
	
	# MultiplayerSynchronizer uses MultiplayerAPI::decode_and_decompress_variants()
	# which handles both compressed (BOOL/INT) and uncompressed variants
	# For this test, we'll decode each variant using bytes_to_var() which is
	# what the decompression function uses internally
	
	var offset = 0
	var variant_count = 0
	var pass_count = 0
	var fail_count = 0
	
	while offset < data.size():
		# Slice remaining data
		var remaining_data = data.slice(offset)
		
		# Try to decode one variant using bytes_to_var (what MultiplayerAPI uses)
		var variant = bytes_to_var(remaining_data)
		if variant == null:
			print("  ❌ Variant ", variant_count + 1, ": Failed to decode at offset ", offset)
			fail_count += 1
			break
		
		# Calculate size by re-encoding
		var encoded = var_to_bytes(variant)
		var variant_size = encoded.size()
		
		variant_count += 1
		var type = typeof(variant)
		var type_names = ["NIL", "BOOL", "INT", "FLOAT", "STRING", "VECTOR2", "RECT2", "VECTOR3", "TRANSFORM2D", "VECTOR4", "PLANE", "QUATERNION", "AABB", "BASIS", "TRANSFORM3D", "PROJECTION", "COLOR", "STRING_NAME", "NODE_PATH", "RID", "OBJECT", "CALLABLE", "SIGNAL", "DICTIONARY", "ARRAY", "PACKED_BYTE_ARRAY", "PACKED_INT32_ARRAY", "PACKED_INT64_ARRAY", "PACKED_FLOAT32_ARRAY", "PACKED_FLOAT64_ARRAY", "PACKED_STRING_ARRAY", "PACKED_VECTOR2_ARRAY", "PACKED_VECTOR3_ARRAY", "PACKED_COLOR_ARRAY"]
		var type_name = type_names[type] if type < type_names.size() else "UNKNOWN"
		
		print("  ✓ Variant ", variant_count, ": ", type_name, " = ", _variant_to_string(variant), " (", variant_size, " bytes)")
		pass_count += 1
		
		offset += variant_size
		
		if variant_size == 0:
			print("⚠️  Variant size is 0, stopping")
			break
	
	print("")
	print("Results: ", pass_count, "/", variant_count, " variants decoded successfully")
	
	if fail_count == 0 and variant_count > 0:
		print("✅ PASS: All variants decoded using MultiplayerSynchronizer's method")
		print("   Our encoding is compatible with MultiplayerAPI::decode_and_decompress_variants()")
	else:
		print("❌ FAIL: ", fail_count, " variants could not be decoded")
		print("   Encoding may not be compatible with MultiplayerSynchronizer")

func test_full_sync_packet_decoding():
	print("")
	print("Test 2: Full Sync Packet Decoding (from Elixir)")
	print("------------------------------------------------")
	
	# Read the actual packet generated by our Elixir encoder
	var file = FileAccess.open(test_full_sync_file, FileAccess.READ)
	if file == null:
		print("⚠️  Skipping: Could not open #{test_full_sync_file}")
		print("   Run test_multisync_packet.exs first to generate the file")
		return
	
	var packet = file.get_buffer(file.get_length())
	file.close()
	
	print("Read ", packet.size(), " bytes from Elixir-generated full sync packet")
	print("")
	print("Decoding using MultiplayerSynchronizer's on_sync_receive() logic:")
	print("")
	
	# Simulate MultiplayerSynchronizer's on_sync_receive() from scene_replication_interface.cpp
	# This is the ACTUAL code path MultiplayerSynchronizer uses
	
	if packet.size() < 11:
		print("❌ FAIL: Packet too small (MultiplayerSynchronizer requires at least 11 bytes)")
		return
	
	# Check command
	var command = packet[0]
	var is_delta = (command & (1 << 4)) != 0  # CMD_FLAG_0_SHIFT = 4
	
	if is_delta:
		print("❌ FAIL: Expected full sync packet, got delta sync")
		return
	
	if command != 0x01:  # NETWORK_COMMAND_SYNC
		print("❌ FAIL: Invalid command: 0x", String.num(command, 16))
		return
	
	# Read network time (full sync only)
	var network_time = packet[1] | (packet[2] << 8)
	var offset = 3
	
	print("  ✓ Command: 0x", String.num(command, 16), " (NETWORK_COMMAND_SYNC)")
	print("  ✓ Network Time: ", network_time)
	print("")
	
	# Process synchronizers (as MultiplayerSynchronizer does)
	var sync_count = 0
	
	while offset + 8 < packet.size():
		# Read net_id and data_size (as MultiplayerSynchronizer does)
		var net_id = _decode_uint32(packet, offset)
		offset += 4
		var data_size = _decode_uint32(packet, offset)
		offset += 4
		
		if data_size > packet.size() - offset:
			print("  ⚠️  Synchronizer ", sync_count + 1, ": Data size (", data_size, ") exceeds remaining packet")
			break
		
		print("  Synchronizer ", sync_count + 1, ":")
		print("    Net ID: ", net_id)
		print("    Data Size: ", data_size, " bytes")
		
		# Extract variant data
		var variant_data = packet.slice(offset, offset + data_size)
		
		# Decode using MultiplayerAPI::decode_and_decompress_variants()
		# For this test, we use bytes_to_var() which is what the decompression uses
		var variant = bytes_to_var(variant_data)
		
		if variant == null:
			print("    ❌ FAIL: Could not decode variant data")
			print("    This means MultiplayerSynchronizer would fail to process this packet")
			return
		
		print("    ✓ Variant decoded successfully")
		print("    ✓ Type: ", typeof(variant))
		
		if variant is Dictionary:
			print("    ✓ Dictionary size: ", variant.size(), " keys")
			if variant.has("node_type"):
				print("    ✓ Contains 'node_type': ", variant["node_type"])
		
		offset += data_size
		sync_count += 1
		
		# Safety limit
		if sync_count > 10:
			break
	
	print("")
	if sync_count > 0:
		print("✅ PASS: Full sync packet decoded successfully")
		print("   MultiplayerSynchronizer's on_sync_receive() would process this packet correctly")
	else:
		print("❌ FAIL: No synchronizers found in packet")

func test_delta_sync_packet_decoding():
	print("")
	print("Test 3: Delta Sync Packet Decoding (from Elixir)")
	print("-------------------------------------------------")
	
	# Read the actual packet generated by our Elixir encoder
	var file = FileAccess.open(test_delta_sync_file, FileAccess.READ)
	if file == null:
		print("⚠️  Skipping: Could not open ", test_delta_sync_file)
		print("   Run test_multisync_delta_packet.exs first to generate the file")
		return
	
	var packet = file.get_buffer(file.get_length())
	file.close()
	
	print("Read ", packet.size(), " bytes from Elixir-generated delta sync packet")
	print("")
	print("Decoding using MultiplayerSynchronizer's on_delta_receive() logic:")
	print("")
	
	# Simulate MultiplayerSynchronizer's on_delta_receive() from scene_replication_interface.cpp
	# This is the ACTUAL code path MultiplayerSynchronizer uses for delta sync
	
	if packet.size() < 13:
		print("❌ FAIL: Packet too small (delta sync requires at least 13 bytes)")
		return
	
	# Check command
	var command = packet[0]
	var is_delta = (command & (1 << 4)) != 0  # CMD_FLAG_0_SHIFT = 4
	
	if not is_delta:
		print("❌ FAIL: Expected delta sync packet, got full sync")
		return
	
	var offset = 1
	
	print("  ✓ Command: 0x", String.num(command, 16), " (NETWORK_COMMAND_SYNC | CMD_FLAG_0)")
	print("")
	
	# Process synchronizers (as MultiplayerSynchronizer does for delta)
	var sync_count = 0
	
	while offset + 16 < packet.size():
		# Read net_id, indexes, and data_size (as MultiplayerSynchronizer does)
		var net_id = _decode_uint32(packet, offset)
		offset += 4
		var indexes = _decode_uint64(packet, offset)
		offset += 8
		var data_size = _decode_uint32(packet, offset)
		offset += 4
		
		if data_size > packet.size() - offset:
			print("  ⚠️  Synchronizer ", sync_count + 1, ": Data size (", data_size, ") exceeds remaining packet")
			break
		
		print("  Synchronizer ", sync_count + 1, ":")
		print("    Net ID: ", net_id)
		var indexes_hex = String.num(indexes, 16)
		var indexes_padded = "0".repeat(16 - indexes_hex.length()) + indexes_hex
		print("    Indexes: 0x", indexes_padded, " (bitmask)")
		print("    Data Size: ", data_size, " bytes")
		
		# Extract variant data
		var variant_data = packet.slice(offset, offset + data_size)
		
		# Decode using MultiplayerAPI::decode_and_decompress_variants()
		var variant = bytes_to_var(variant_data)
		
		if variant == null:
			print("    ❌ FAIL: Could not decode variant data")
			print("    This means MultiplayerSynchronizer would fail to process this packet")
			return
		
		print("    ✓ Variant decoded successfully")
		print("    ✓ Type: ", typeof(variant))
		
		if variant is Dictionary:
			print("    ✓ Dictionary size: ", variant.size(), " keys")
		
		offset += data_size
		sync_count += 1
		
		# Safety limit
		if sync_count > 10:
			break
	
	print("")
	if sync_count > 0:
		print("✅ PASS: Delta sync packet decoded successfully")
		print("   MultiplayerSynchronizer's on_delta_receive() would process this packet correctly")
	else:
		print("❌ FAIL: No synchronizers found in packet")

func test_multisync_receive_handler():
	print("")
	print("Test 4: MultiplayerSynchronizer Receive Handler Simulation")
	print("-----------------------------------------------------------")
	
	# This test simulates what MultiplayerSynchronizer's on_sync_receive() does
	# It reads the packet format and extracts synchronizer data
	
	var file = FileAccess.open(test_full_sync_file, FileAccess.READ)
	if file == null:
		print("⚠️  Skipping: Could not open #{test_full_sync_file}")
		print("   Run test_multisync_packet.exs first to generate the file")
		return
	
	var packet = file.get_buffer(file.get_length())
	file.close()
	
	print("Read ", packet.size(), " bytes from full sync packet")
	print("")
	
	# Simulate MultiplayerSynchronizer's packet processing
	# From scene_replication_interface.cpp:on_sync_receive()
	
	var offset = 0
	
	# Read command
	var command = packet[offset]
	offset += 1
	
	# Check if it's a sync command
	if command != 0x01 and (command & 0x0F) != 0x01:
		print("❌ FAIL: Not a sync command")
		return
	
	# Check if it's delta (has CMD_FLAG_0)
	var is_delta = (command & (1 << 4)) != 0
	
	if is_delta:
		print("  Packet type: Delta Sync")
	else:
		print("  Packet type: Full Sync")
		
		# Read network time (only in full sync)
		var net_time = packet[offset] | (packet[offset + 1] << 8)
		offset += 2
		print("  Network Time: ", net_time)
	
	# Process synchronizers (simplified - just verify we can read the structure)
	var sync_count = 0
	
	while offset + 8 < packet.size():
		var net_id = _decode_uint32(packet, offset)
		offset += 4
		
		if is_delta:
			var indexes = _decode_uint64(packet, offset)
			offset += 8
			print("  Synchronizer ", sync_count + 1, ": Net ID=", net_id, ", Indexes=0x", String.num(indexes, 16))
		else:
			var data_size = _decode_uint32(packet, offset)
			offset += 4
			print("  Synchronizer ", sync_count + 1, ": Net ID=", net_id, ", Data Size=", data_size)
			
			# Verify we can decode the variant data
			if offset + data_size <= packet.size():
				var variant_data = packet.slice(offset, offset + data_size)
				var variant = bytes_to_var(variant_data)
				
				if variant != null:
					print("    ✓ Variant decoded successfully")
				else:
					print("    ❌ Failed to decode variant")
					return
				
				offset += data_size
			else:
				print("    ⚠️  Data size exceeds packet")
				break
		
		sync_count += 1
		
		# Safety limit
		if sync_count > 10:
			break
	
	print("")
	print("  Processed ", sync_count, " synchronizers")
	print("✅ PASS: Packet structure compatible with MultiplayerSynchronizer's receive handler")

# Helper: Encode uint32 as little-endian
func _encode_uint32(value: int) -> PackedByteArray:
	var bytes = PackedByteArray()
	bytes.append(value & 0xFF)
	bytes.append((value >> 8) & 0xFF)
	bytes.append((value >> 16) & 0xFF)
	bytes.append((value >> 24) & 0xFF)
	return bytes

# Helper: Decode uint32 from little-endian
func _decode_uint32(data: PackedByteArray, offset: int) -> int:
	return data[offset] | (data[offset + 1] << 8) | (data[offset + 2] << 16) | (data[offset + 3] << 24)

# Helper: Encode uint64 as little-endian
func _encode_uint64(value: int) -> PackedByteArray:
	var bytes = PackedByteArray()
	for i in range(8):
		bytes.append((value >> (i * 8)) & 0xFF)
	return bytes

# Helper: Decode uint64 from little-endian
func _decode_uint64(data: PackedByteArray, offset: int) -> int:
	var result = 0
	for i in range(8):
		result |= (data[offset + i] << (i * 8))
	return result

func _variant_to_string(variant) -> String:
	var type = typeof(variant)
	match type:
		TYPE_NIL:
			return "NIL"
		TYPE_BOOL:
			return "BOOL: " + str(variant)
		TYPE_INT:
			return "INT: " + str(variant)
		TYPE_FLOAT:
			return "FLOAT: " + str(variant)
		TYPE_STRING:
			return "STRING: \"" + str(variant) + "\""
		TYPE_VECTOR3:
			return "VECTOR3: " + str(variant)
		TYPE_QUATERNION:
			return "QUATERNION: " + str(variant)
		TYPE_DICTIONARY:
			return "DICTIONARY: " + str(variant.size()) + " keys"
		TYPE_ARRAY:
			return "ARRAY: " + str(variant.size()) + " elements"
		_:
			return "TYPE_" + str(type) + ": " + str(variant)

